name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==1.7.1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - uses: pre-commit/action@v3.0.0
      - name: Run flake8
        run: poetry run ruff .
      - name: Run pyright
        run: poetry run pyright .
